### ISSUE TITLE
Copy image fails in remote mode

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1007]
**Steps to Reproduce**

1. Checkout latest version of release/2.4 branch
2. `yarn install`, `yarn build`, `yarn serve:remote`
3. Open Ketcher at `http://localhost:4001/?api_path=https://lifescience.opensource.epam.com/v2` or specify a different endpoint
4. Add a molecule from template, or just a circle
5. Select all with select tool or with Ctrl + A
6. Go to Copy dropdown menu, select Copy Image

**Expected behavior**
Image is copied to clipboard and can then be pasted into a text editor like MS Word.

**Actual behavior**
An error is shown that feature is not supported by browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/18420141/143047218-898ad73c-29e9-40e3-b2fd-e1e67aa0464a.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1 Monterey
 - Browsers: Chrome, Edge, Firefox

**Additional context**
Feature seems to work fine in standalone mode in Chrome and Edge.

**Comment by AllaZhbanova** [comment]
The issue is clone of https://github.com/epam/ketcher/issues/371

**Comment by AllaZhbanova** [comment]
The issue is in Error message as well, as this feature is available for the browser. Only IE browser does not support the Copy Image action
Response: <?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200" viewBox="0 0 200 200">
</svg>
