### ISSUE TITLE
Redesign of Select component

### ISSUE THREAD

**Issue by ViktoriiaFedotkina** [epam/ketcher#1056]
Change the visual representation of Select and refactor it

![Screen Shot 2021-12-03 at 1 40 41 PM](https://user-images.githubusercontent.com/94109373/144589372-f69e997d-747f-442a-8e20-424f568a6707.png)

**Comment by akolyakov42** [comment]
Issue is reopened because of a problem with selector in **S-Group Properties** window.
Dropdown drops "into" floating window and can be seen only using mouse scrolling wheel. Scrollbar also works incorrect.

https://user-images.githubusercontent.com/97884482/151807105-ea3ba841-f960-4b48-b651-d83483da581a.mov
