### ISSUE TITLE
Shift between pointer and atom

### ISSUE THREAD

**Issue by dmoskalenko-datagrok** [epam/ketcher#1272]
**Condition**
Having parent DIV with style  _max-height: 80vh_;

<img src="https://user-images.githubusercontent.com/98885254/154633577-e638f6f4-c916-437d-aeee-ba0994b71987.png" width="400">

lead to an issue with the shift between atoms and mouse pointer.

**Expected behavior**
The pointer should always select an atom under it.

**Screenshots**
<img src="https://user-images.githubusercontent.com/98885254/154641859-eaf0ffd6-dc0b-43ae-b7b2-4f41f8296da6.gif" width="500">

**Comment by AndreiMazol** [comment]
Dear @dmoskalenko-datagrok ,

can you  check if issue is still reproducible in case if Ketcher Editor is fully embedded into parent element without necessity to show vertical/horizontal scrolls. To embed Ketcher please follow this instructions:  https://github.com/epam/ketcher/discussions/583#discussioncomment-841139

Looking forward for your reply.

Regards,
Andrei

**Comment by karen-sarkisyan** [comment]
Hi @dmoskalenko-datagrok ,

I've reproduced your case. Indeed, when Ketcher has a scrollable parent, positioning of cursor on the canvas might break.

However, Andrei's comment above still applies: try embedding your element in a way that will avoid scrolling relative to the `body`. When editor is fully embedded into page, and is scrolled along with it, it will work as expected (as in our [demo](https://lifescience.opensource.epam.com/ketcher/demo/ketcher_2_3_remote.html)).

We're going to improve this behaviour so that it will work in your case too, but we'll do it in scope of release 2.5, so you might want to use the fix we suggest until then.
