### ISSUE TITLE
update indigo version

### ISSUE THREAD

**Issue by AnaMoskvina** [epam/ketcher#1556]

**Comment by ZhannaNovikova** [comment]
Verified in the Remote mode
Indigo version has been updated to Version 1.6.6.0-g5ccc3637b-wasm32-wasm-clang-13.0.0, but after clicking on the About button, shows incorrect version

**Steps to reproduce:**

1. Launch Ketcher with the Remote mode
2. Click on the About button

**Expected behavior:**
Correct version number is shown

**Actual behavior:**
The incorrect version 1.6.1.10-gd1a8a571b-x86_64-linux-gnu-10.2.1 is shown
Related issue https://github.com/epam/ketcher/issues/1569

Verified in the Standalone mode,
Indigo version has been updated to Version 1.6.6.0-g5ccc3637b-wasm32-wasm-clang-13.0.0
