### ISSUE TITLE
Move to vite from react-app-rewired for example project development build 

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2411]
**Background**
We are currently using rollup.js for building the project, this library seems to be outdated and we have problems with builds taking too much time.

**Solution**
We would like to switch to a different build library, vite.js seems like a good solution: https://vitejs.dev
- it uses the same cli and plugin apis that are used by rollup.js, so the switch should not be too hard in terms of code changes
- it promises big gains in build time

**Alternatives**
- switching to other build engines

**Additional context**
As part of this ticket, we would like to try and switch the build process from using rollup to using vite, this will involve updating all package.json files across ./packages and ./example and testing the local build timing on various systems

**Comment by yuleicul** [comment]
Hi 👋 I have a question here. I just did some research, and I found Vite does provide a faster **development** experience because it supports **unbundled** ESM in development. As for production, it uses Rollup to bundle the code under the hood.

The Ketcher codebase is a monorepo If I understand correctly, so we have to build packages every time we develop. Just like every time we develop in localhost, we should run `yarn start` (`npm start` after #2008) in `/packages/ketcher-core`, `/packages/ketcher-react` and so on. In `/packages/ketcher-core/package.json` we can see `yarn start` equals to `rollup --watch` which means we just watch the new change and bundle with Rollup again.

If I replace Rollup with Vite, I'd probably want to make `npm start` equal to something like `vite build --watch` which runs rollup under the hood, so we are not gonna have the *faster development experience* because we don't use `vite dev`.

Maybe I'm wrong, but If there are some ways we can use `vite dev` when developing in a monorepo, then I believe the development experience will level up.

**Comment by yuleicul** [comment]
My plan to switch to Vite is:

For /packages
1. Rewrite `rollup.config.js` to `vite.config.js`
2. Update scripts: 
"build": "cross-env NODE_ENV=production rollup -c -m true"--> "build": "cross-env NODE_ENV=production vite build"
"start": "cross-env NODE_ENV=development rollup -c -m true -w" --> "start": "cross-env NODE_ENV=development vite build -w"

For /example:
1. Replace react-app-rewired with Vite
2. Add new `vite.config.js`


What I'm doing today is try to rewrite `rollup.config.js` to `vite.config.js` in ketcher-core. It's a bit tough because some rollup plugins are not compatible in vite. My next step is to figure out what every plugin does and try to find a vite plugin to replace it. And also I hit some pitfalls.... for example, we use `paths` in tsconfig to map some paths, but vite doesn't recognize them.

My estimate for the whole switch is 5 days. Next week we have a public holiday on Wed, and I want to take two more regular vacations on Mon and Tue. So I'll try to finish by the end of this Friday.

**Comment by yuleicul** [comment]
Have successfully moved to Vite in ketcher-core, but the build speed is almost the same as before. 

Today I was working on rewriting `rollup.config.js` to `vite.config.js` in ketcher-react, but I hit some pitfalls. Just trying to resolve them. (Vite has a lot of built-in plugins)

What enlightened me is
> This is just a PoC, may be you don't need to support all the plugins we have or some other stuff to do.
> We just need to understand:
> – Is it possible to migrate to other tool?
> – If yes, what benefits we will receive?
> – If no, then why? And what needs to be done to become "yes"
> -- @Nitvex 

So I think I need to change my mind. My plan for tomorrow:
- [ ] Create a new app with vite and try to use [linked dependencies](https://vitejs.dev/guide/dep-pre-bundling.html#monorepos-and-linked-dependencies) to speed up development experience

**Comment by yuleicul** [comment]
## Proposed solutions

Vite for development, Rollup for build. 

For development, to create a new dev workspace by Vite, e.g. `/dev`. Its functionality equals to current `/example`, but engined by Vite which will make the development faster.

For build, keep current Rollup configurations and the **build** workflow the same.

## New development workflow

In root

```shell
npm install
```

In `/dev`

```shell
# For standalone
npm run start:standalone

# For remote
npm run start:remote
```

**NB!** Before creating a PR, you'd better preview your implementation to make sure everything works fine by Rollup. Please follow DEVNOTES -> Development to preview.

## Why

### Why not replace Rollup with Vite?

It'll take more effort, but the optimization is a little or even none.

Ketcher uses Rollup to build libraries. If we replace Rollup with Vite, that means we use Vite to build libraries. As for build, Rollup is not worse than Vite which uses Rollup under the hood.

I've taken two days to replace Rollup with Vite in ketcher-core and ketcher-react, but as I thought, optimizations are a little or even none. 

> The following data is based on my Windows 10, with 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz 2.61 GHz.

For **ketcher-core**, the build time changes from **11.5s** to **13.49s** 

![ketcher-core-rollup](https://user-images.githubusercontent.com/27288153/228761212-f6664e79-6ae7-4316-a1f0-012f9196806e.png)

![ketcher-core-vite](https://user-images.githubusercontent.com/27288153/228761280-0e085140-dfd4-4fbc-b869-defdfe44010d.png)

For **ketcher-react**, the build time changes from **23.9s** to **20.42s**

![ketcher-react-rollup](https://user-images.githubusercontent.com/27288153/228761327-6363012c-c0bf-46b3-9f62-6a2f384d3747.png)

![ketcher-react-vite](https://user-images.githubusercontent.com/27288153/228761343-adeefaa4-c9bf-464b-8e44-cc235b913290.png)

### Why Vite for development?

Easy to answer, because Vite is fast for development. [[Vite]] leverages native [[ES Modules]] in the browser to load your code instantly, no matter how large the App is. Instead of importing a single JavaScript bundle file, it's importing our actual source code, like a raw `.tsx` file. It also makes TypeScript about 20–30 times faster because it skips type checking and uses [[esBuild]] to transpile your code. Vite also supports [[Hot Module Replacement]] for an extremely fast feedback loop during development.

I've finished a small demo below. Compared to approximately more than 30s to wait after changes when developing, Vite just needs less than 10s.

https://user-images.githubusercontent.com/27288153/228762340-9f8a9813-a72a-41e0-812c-34e368578a31.mp4

## Next steps

Just as I mentioned above, what I need to implement is the new dev workspace `/dev`. I've successfully run ketcher-react in the dev workspace. However, as you can see in the recording, there are still some bugs, like wired styles and lots of warnings/errors in the browser console, so my next step will be:

- [ ] To fix bugs when running ketcher-react
- [ ] To run other packages in `/dev`, including ketcher-core, ketcher-standalone, and ketcher-polymer-editor
- [ ] To make sure the new development workflow above works fine

Trying to finish them by the end of this week.
