### ISSUE TITLE
How to use as a react component?

### ISSUE THREAD

**Issue by Theophylline** [epam/ketcher#265]
Hi,

I'm new to React so apologies if these are trivial questions, but I'm running into a few issues when using this as a react component:

1) I installed via npm and followed your example, but I got "Attempted import error: 'RemoteStructServiceProvider' is not exported from 'ketcher-react'." after `npm start`
2) Is it possible to adjust the size of the editor? Currently it takes up the whole page
3) Is it possible to export the structure drawn by the user as SMILES string?

Thank you!

**Comment by AndreiMazol** [comment]
Hi @Theophylline ,

1. You need to create your own example app or use the whole code from master branch - see DEVNOTES.md for details (npm package of ketcher-react v.2.1.0 does not contain RemoteStructServiceProvider yet. This module will be delivered as a part of the next release in order to  support remote/standalone modes)
2. If you  want to change the size of the editor you  can do it by overriding CSS styles.
3. Ketcher object (window.ketcher) provides different methods that allow  to transform rendered structure to *.mol, *.smi and *.ket formats:
`ketcher.getMolfile()`
`ketcher.getSmiles()`
`ketcher.toGraph()`

Best regards,
Ketcher team
