### ISSUE TITLE
Horizontal and vertical flips are working incorrectly (affect position) with some atoms, texts and functional groups

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2805]
**Steps to Reproduce**
1. Open Ketcher
2. Add Functional Group ( e.g. Boc ) on canvas
3. Expand it and select
4. Start pressing Vertical Flip button above selection

**Actual behavior**
- Expanded Functional Group starts moving down on canvas after each vertical flip.
- Single atoms (moleculas) with numeric in the name (CH4 as example) starts moving down on canvas after each vertical flip.
- Single atoms (moleculas) with numeric in the name (CH4 as example) starts moving right on canvas after each horizontal flip.
- Text multi row containers starts moving down on canvas after each vertical flip.

**Expected behavior**
- Expanded Functional Group only flip without moving down or other direction.
- Single atoms (moleculas) with numeric in the name (CH4 as example) stays on their previous position after double vertical flip.
- Single atoms (moleculas) with numeric in the name (CH4 as example) stays on their previous position after double horizontal flip.
- Text multi row containers stays on their previous position after double vertical flip.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/c7722d48-8f95-40fa-956c-91cd34ae95b8

The wrong behaviour for flip for two simple moleculas:

https://github.com/epam/ketcher/assets/6398891/cbac9604-00b1-41de-b753-5601a0761047

The wrong behaviour for flip for text container:

https://github.com/epam/ketcher/assets/6398891/fbdd343f-ef65-46b2-9faf-04ccce4cc15c

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.12.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by kaluginserg** [comment]
Simplified issue reproduction:
First has problem, second doesn't:
![Screenshot 2023-06-28 at 19 25 26](https://github.com/epam/ketcher/assets/6398891/e7267529-5828-4c44-9fcb-ec7c14f80dec) ![Screenshot 2023-06-28 at 19 25 11](https://github.com/epam/ketcher/assets/6398891/2a2d3e45-d5f1-4c4f-a97b-66bb12bce60d)

Reason of the issue: we get the Bounding box center, and based on it we flip the coordinates for the atoms.
But bounding box is not connected with atom positions, it's connected to text labels about atoms - so that's why we have issue. It atoms have same Text balance (half of vertical size) - they flipped correctly.

**Comment by kaluginserg** [comment]
Even more simpler @Zhirnoff 

The wrong behaviour for flip for two simple moleculas:

https://github.com/epam/ketcher/assets/6398891/cbac9604-00b1-41de-b753-5601a0761047


Incorrect rotate tool for:
- **Horizontal** flip
- **Vertical** flip

**Comment by kaluginserg** [comment]
Additional issue with rotation center (fixed in the PR #2827, reasons of issue: #2739 and #2467 )

https://github.com/epam/ketcher/assets/6398891/523fdd84-0ac3-45d5-8e78-301ec81483c2
