### ISSUE TITLE
'Calculated values' - Error messages are different in 'Remote' and 'Standalone' modes

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#427]
Affected Version: Standalone, Remote
_Scenario 1_

Steps to Reproduce:
1. Launch Ketcher (Remote)
2. Draw a structure on the canvas, e.g. cyclohexane
3. With the R-Group Label Tool set any label for any structure atom, for example, R1
4. Click the 'Calculated Values' button
5. Click 'Close' button
6. Click the 'Calculated Values" button again
7. Repeat steps 1-6 in Standalone mode

Expected result:
4. Error messages are the same in Remote and Standalone modes.
6. No active cursor in shown in 'Molecular Weight', 'Exact Mass', 'Elemental Analysis' fields

Actual result: 
4. Remote mode - 'error: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites'.
Standalone mode - 'mass: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites'.
6. In the 'Molecular Weight' field the end of the error message is shown with the active cursor in the end of the line.
<img width="960" alt="Cursor" src="https://user-images.githubusercontent.com/80695128/112798914-48fccd80-9076-11eb-9ce9-2414b0f6cde8.png">

_Scenario 2_
Steps:
1. Launch Ketcher
2. Open [Attachment_points.zip](https://github.com/epam/ketcher/files/6829418/Attachment_points.zip)
3. Click Calculated Values button

Expected result:
"Cannot calculate properties for RGroups" in all of the fields of the window in remote and standalone mode

Actual result:
Standalone mode has alert window:
![image](https://user-images.githubusercontent.com/87320094/125923945-35e3c27d-f722-495b-8293-3cda6df43cc0.png)

_Scenario 3_
Steps:
1. Launch Ketcher
2. Open [SRU-polymer.zip](https://github.com/epam/ketcher/files/6829676/SRU-polymer.zip)
3. Click Calculated Values button

Expected result: Chemical Formula field contains correct information (C9H20(C6H12)n). Other fields have "Cannot calculate mass for structure with repeating units" in remote and standalone mode

Actual result:
Chemical Formula field contains correct information (C9H20(C6H12)n). Other fields have:
Remote mode - 'error: Cannot calculate mass for structure with repeating units'.
Standalone mode - 'mass: Cannot calculate mass for structure with repeating units'.

_Scenario 4_
Steps:
1. Launch Ketcher
2. Open [06-AQuery-NonHSub.zip](https://github.com/epam/ketcher/files/6830124/06-AQuery-NonHSub.zip) 
3. Click Calculated Values button

Expected result:
All fields contains "Cannot calculate properties for structures with query features" message in both standalone and query mode. Text can be moved with cursor.

Actual result:
Standalone mode has alert window:
![image](https://user-images.githubusercontent.com/87320094/125936913-555dc197-afa5-4cef-88de-a1a318c8b5cc.png)
Remote mode: all fields contains "Cannot calculate properties for structures with query features" message. Chemical Formula field has text that can not be moved with cursor.

**Comment by Svetlana-Asinovskaia** [comment]
Related issue: https://github.com/epam/Indigo/issues/383

**Comment by Svetlana-Asinovskaia** [comment]
Related issue: https://github.com/epam/Indigo/issues/384

**Comment by nseufulina** [comment]
**Steps:**
1.Open
[31LHIS_ringbond.zip](https://github.com/epam/ketcher/files/6823885/31LHIS_ringbond.zip)
2. Click Calculated Values button

**Actual result:**
Alert with information instead of it's display in the Calculated Values window in **standalone** mode
![image](https://user-images.githubusercontent.com/87320094/125806163-bd931dfa-780a-43ed-aa76-4cdc98eb61e2.png)

remote mode:
![image](https://user-images.githubusercontent.com/87320094/125806229-17962956-ec2a-4b36-8893-1a6da54fec7b.png)

**Expected result:**
Information in remote and standalone mode displayed identically

**Comment by nseufulina** [comment]
Steps:
1.Open
[R-Group (1).zip](https://github.com/epam/ketcher/files/6828569/R-Group.1.zip)
2. Click Calculated Values button

Actual result:
Alert with information instead of it's display in the Calculated Values window in standalone mode
![image](https://user-images.githubusercontent.com/87320094/125907224-b1768163-6df2-497f-9767-9049a3fe7d7b.png)

Expected result:
Information in remote and standalone mode displayed identically: all fields contain 'Cannot calculate properties for RGroups' message
