### ISSUE TITLE
Add possibility to save structure as PNG

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#437]
Ketcher API provides a method to save structure as SVG and PNG files by calling Indigo endpoints. In scope of this task is necessary to rework 'Save' dialog in order to  support possibility to save structure in different graphic formats (SVG and PNG).

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is closed as partly fixed. 
It's possible to save the structure as image in Standalone mode (as svg and png), in Remote mode (as svg). It will be possible to save the structure as png in Remote mode after the fix of the issue https://github.com/epam/ketcher/issues/371 will be done. Besides the sizes of the view boxes are different in Remote and Standalone modes now. It has been decided that the problems are not blocking, since the main functionality works correctly. Behavior will be rechecked after the fixes.
