### ISSUE TITLE
Moodle Plugin Doubt

### ISSUE THREAD

**Issue by registerme1963** [epam/ketcher#4440]
I successfully created Ketcher standalone mode plugin for Moodle 4.3 TinyMCE editor. I see the main##.js is about 20MB. Since my primary interest is drawing chemical structures, is it possible to load relevant chunk from the main.js. Something like <src="main.js?drawonly"> 
How does the 20MB file is loaded in slow network? Can somebody explain me?
thanks and regards
rV

**Comment by rrodionov91** [comment]
Hi @registerme1963 

Thank you for raising this issue.

Currently ketcher standalone bundle size is about 20MB because it contains indigo wasm build which includes binary data.
We are currently working on separation binary part to different file and loading it asynchronously after ketcher initialization. (related indigo ticket https://github.com/epam/Indigo/issues/877).

Also there is an option to use ketcher remote. The size of bundle there is 4.4MB currently. However you will need to run indigo remote somewhere on your environment.

Do you use gzip compression on your server side? It should reduce loading time significally.

**Comment by registerme1963** [comment]
Thank you. Gzip is enabled. Waiting for the new version.
