### ISSUE TITLE
View only mode

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#4965]
As an **Application Administrator**, I want the ability to configure Ketcher into a **view-only mode** so that I can control user interactions and limit modifications to the chemical structures. The view-only mode should be configurable from **settings on load** and by **Ketcher API in runtime**.

**Acceptance Criteria:**

1. An Application Administrator should be able to configure Ketcher into a view-only mode from settings **before web app load**.
2. The Application Administrator should also be able to switch Ketcher **into and out of view-only mode in runtime** using the Ketcher API.
3. In view-only mode, **all editing tools should be disabled including hotkeys**, preventing users from modifying the chemical structures.
4. The following tools and functions should be enabled:
    1. Open, Save, Copy group
![image](https://github.com/user-attachments/assets/30d48cc4-7c4d-4975-b890-4fa3f0cbd665)
    2. Hand and Selection tools
![Image](https://github.com/user-attachments/assets/7ea5d41e-4b99-4963-9006-b3eab698872d)
    3. Check Structure, Calculated Values, 3D Viewer
![Image](https://github.com/user-attachments/assets/f013bc38-1227-4a88-997a-3ae9769d0d87)
![Image](https://github.com/user-attachments/assets/68672947-c91b-4ff0-a849-10896849905d)

5. "Add to Canvas" button should be disabled in the "Open structure" dialog window and "Open as New Project" must be highlighted as default.
![image](https://github.com/user-attachments/assets/96eed4c0-8cd3-4e63-b715-ec7399d7a236)

6. When the user is using Ketcher and has any tool selected, switching to View Only mode will automatically reset the selected tool to "Rectangle Selection."

7. To turn on/turn off option use this command in console with true and false flag: ketcher.editor.options({ viewOnlyMode: true })

8. [Hotkeys](https://github.com/epam/ketcher/blob/master/documentation/help.md#hotkeys) whitelist:

Shortcut | Action
-- | --
Mod+o | Open…
Mod+s | Save As…
Mod+c | Copy
Mod+Shift+f | Copy Image
Mod+m | Copy as MOL
Mod+Shift+k | Copy as KET
Mod+a | Select All
Mod+Shift+a | Deselect All
Alt+s | Check structure
Alt+c | Calculate values
Mod+h | Hand tool
Escape only switch to Selection | Rotate between by Shift+Tab: Lasso Selection, Rectangle Selection, Fragment Selection
Mod+_, Mod+- | Zoom Out
Mod+=, Mod++ | Zoom In
Mod+Shift+0 | Zoom 100%
?, &, Shift+/ | Help

**Comment by daniil-sloboda** [comment]
* Right click on any element should not display context menu
* Selection tool should not allow to move or resize elements, only select them
* Whenever view mode is triggered tool should reset to selection

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]

1) Currently, there are issues with selecting structures using the Fragment tool (it’s not working).
2) Some hotkeys are not functioning (see screenshot). Mod+d Select descriptors not working also in prod version at all.
I change description in ticket about Escape hotkey because we change it behaviour in https://github.com/epam/ketcher/issues/2127
![2024-09-11_15h42_13](https://github.com/user-attachments/assets/b71edd70-0e5b-4ebb-94a9-34f7c32bf6fb)

3) After disabling View Only mode, it’s impossible to select all structures and move them together to a new place on the canvas.

https://github.com/user-attachments/assets/4bce8afe-51c4-4769-a68e-aad140b48f72


4) Through 3D View, it’s possible to change the structure's position on the canvas (we need to decide whether to completely remove the 3D Viewer or block the Apply button in it).
5) Full screen, Help, and About buttons are blocked in View Only mode (is it necessary to block them?).
6) Also, after enabling View Only mode via API, the structure shifts to the center of the canvas. This requires further investigation (a bug will be logged).

**Comment by Zhirnoff** [comment]
Tested.
![2024-10-08_16h08_23](https://github.com/user-attachments/assets/ba5f8e96-a60a-4f88-8afc-5a15936d9dab)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
