### ISSUE TITLE
SMILES for two arrows reaction works wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5641]
**Steps to Reproduce**
1. Go to Micromolecules mode
2. Load from file: [two-arrows-and-plus.zip](https://github.com/user-attachments/files/17257708/two-arrows-and-plus.zip)
![image](https://github.com/user-attachments/assets/1058198a-40f2-490c-9b34-92b1ca065c8e)
3. Open console and run: `await ketcher.getSmiles()`

**Actual behavior**
System returns: `C1C=CC=CC=1.O>>C1C=CC(C)=CC=1C`
![image](https://github.com/user-attachments/assets/d2c14f3d-fcd0-46e5-ab27-7ab71f3fbe1b)

**Expected behavior**
System returns: `C1C=CC=CC=1.O>>C1C=CC(C)=CC=1C.C1C=CC(C)=CC=1C`
![image](https://github.com/user-attachments/assets/255a0f83-0929-4992-a0e1-5cf4a9f0208a)

**Versions**
- Ketcher Version 2.25.0-rc.2 Build at 2024-10-03; 18:30:41
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10

**Comment by samellis** [comment]
I noticed this too. Just to add, from my limited testing of this previously, I believe it's only the final product returned. Not noticeable in this case as the intermediate and product are the same, but if you had A -> B -> C I believe that the returned result would be A->C. Ideal and expected behaviour would be full representation of what is drawn.

**Comment by NataliaLoginova** [comment]
discussed with @AlexeyGirin, this ticket can be closed

**Comment by AlexeyGirin** [comment]
Not a bug.
