### ISSUE TITLE
Bond length is different for monomers loaded from HELM and from the library

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#6026]
**Steps to Reproduce**
1. Go to Macro - Flex mode
2. Load HELM paste from clipboard way: `RNA1{R(A)P}$$$$V2.0`
![image](https://github.com/user-attachments/assets/c643c964-1247-402a-86b1-6d594e9471ca)
3. Put the same preset from the library and put it above first one

**Actual behavior**
Bond of monomer from the library shorter (1.275 angstroms against 1.5 angstroms from HELM)
![image](https://github.com/user-attachments/assets/e8b78d82-1881-4a80-8c3e-e91275c357fb)

**Expected behavior**
Bonds are equal - 1.5 angstroms
![image](https://github.com/user-attachments/assets/aaf56454-fbdf-429d-9729-3df7cbb00571)

**Versions**
- Ketcher Version 2.28.0-dev.1 Build at 2024-11-28; 06:41:11
- Version 1.27.0-dev.3.0-g62217e49f-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)
- Win10

**Comment by lmhs** [comment]
Bug is relevant for all Presets from RNA group:
for example:
RNA1{R(C)P}$$$$V2.0
or
RNA1{[MOE](A)P}$$$$V2.0

<img width="402" alt="image" src="https://github.com/user-attachments/assets/02838e1c-958b-4631-817c-18e63a3d3c69" />

caused by different calculations based on different RNA monomer distance in presets and values from indigo convert service (when HELM format is used)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2025-01-03_12h40_02](https://github.com/user-attachments/assets/cd5561ed-7e5c-4a17-8de1-f78584bf9c92)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
