### ISSUE TITLE
Adding a stereo flag when opening the structure

### ISSUE THREAD

**Issue by AleksandrPokrovskii** [epam/ketcher#632]
**Steps to Reproduce**
1. Launch Ketcher
2. Add stereo bond (e.g. Single Up Bond)
3. Click the 'Save As' button and save as *.mol file.
4. Open the saved *.mol file.

**Expected behavior**
Stereo flag is not displayed
![image](https://user-images.githubusercontent.com/85170103/125617660-a2d610fc-bf81-44d4-b081-075af82443db.png)

**Actual behavior**
Stereo flag is displayed
![image](https://user-images.githubusercontent.com/85170103/125617637-985119f6-9d0b-4196-8b51-d82baffd1c26.png)

**Additional context**
IE: Adding a stereo flag when copy/paste or cut/paste a stereo bond.

**Comment by nseufulina** [comment]
All bonds from Single/Double bonds segment has this issue:
Expected behavior
Stereo flag is not displayed
![image](https://user-images.githubusercontent.com/87320094/125946643-dd98cc11-dccf-43d8-8153-2668d98ac01f.png)


Actual behavior: 
Stereo flag is displayed
![image](https://user-images.githubusercontent.com/87320094/125946606-f4f96abb-98df-46fc-b11e-f6aa9455c7f9.png)

**Comment by AleksandrPokrovskii** [comment]
The stereo flag is saved when copying, but it should not.

**Steps to Reproduce:**

1.  Launch Ketcher
2. Add chain
3. Add stereo bond (e.g. Single Up Bond)
4. Сopy a part of the structure so that the stereo atom is the last
5. Paste the copied structure

**Expected behavior**
Stereo flag is not displayed
![image](https://user-images.githubusercontent.com/85170103/126297923-1237933a-a2c4-4636-8a86-fe2a55b79936.png)


Actual behavior
Stereo flag is displayed
![image](https://user-images.githubusercontent.com/85170103/126297839-33f0ceed-3751-4e45-b692-38f9830bc7d6.png)
