### ISSUE TITLE
Redo does not work for simple object "Shape line" after moving its dots

### ISSUE THREAD

**Issue by MagomedGasanov** [epam/ketcher#635]
**Steps to Reproduce**
1. Draw line with "Shape Line" tool.
2. Hold the dot at the end of line and change size of the line and its direction.
3. Click "undo"
4. Click "redu"

**Expected behavior**
Redo action correctly displays the initial state of line

**Actual behavior**
Redo action doesn't work, the line and its dots don't change their positions

**Comment by nseufulina** [comment]
Not fixed scenario:
Steps to Reproduce

Draw line with "Shape Line" tool.
Hold the dot at the end of line and change size of the line and its direction.
Click "undo" untill there is no line on the canvas
Click "redu"

Expected behavior
Redo action correctly works

Actual behavior
Redo action return line in the initial state but does not repeat previous actions.
Redo action doesn't work correctly if the line was taken off the canvas by Undo action

**Comment by nseufulina** [comment]
Release/2.3 The issue is closed as fixed.
