### ISSUE TITLE
Setting molekules and adding fragments to ketcher

### ISSUE THREAD

**Issue by sasha-tsepilova** [epam/ketcher#718]
Hi there!
We want to use Ketcher for visualizing molecules in our platform (you can check our GitHub [here](https://github.com/datagrok-ai/public/issues)). Now I'm trying to set molecule with the code provided in the developers manual. I made everything as described and tried standalone and remote Ketcher, but it still doesn't work. I keep getting _"Cannot read property 'setMolecule' of undefined"_ error. Would you mind helping me with some code examples or pointing out my mistakes?
![image](https://user-images.githubusercontent.com/75687119/129683153-55f7f6c6-1f17-4f5b-b87c-60aa488a1992.png)

**Comment by AndreiMazol** [comment]
Hi @sasha-tsepilova ,

I see that the error is happened  because of the fact that ketcher object is not available from your script. I guess Ketcher app and your App are hosted in different domain (because of security reasons, you  cannot get access to global objects that are defined inside Ketcher iframe in such case). 

To fix the issue please choose one of the following:
Option 1:  use the same domain for ketcher app  and your app (for example you  can host Ketcher as a part of your app)
Option 2: use React component library instead of Ready-to-run app. Please look at https://www.npmjs.com/package/ketcher-react
Option 3: use [PostMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to communicate with IFrame (this option does not provided OOTB in Ketcher app yet, so  it is required to  be implemented by your own)

Best regards,
Andrei
