### ISSUE TITLE
If you fuse a ring to an already drawn one that contains a double bond, the bond is overwritten

### ISSUE THREAD

**Issue by robtree** [epam/ketcher#79]
**Steps to reproduce**

1. Go to https://lifescience.opensource.epam.com/ketcher/demo.html
2. Add a benzene ring
3. Fuse a cyclohexane ring to the edge of the benzene ring with a double bond

**Observed results**

The double bond is overwritten.

**Expected results**

The double bond is not overwritten, like Ketcher 1.0.

**Comment by AndreiMazol** [comment]
Dear @robtree,

Thank you for raising this issue.

We made detailed analysis and  we can conclude that it is not a bug because in Ketcher 2.0 the algorithm for working with  templates was changed so this is an expected behavior. Additional details could be found at help page (icon on top menu).

But keeping in mind your observation we are going to review our current approach in  scope of task #95.

Best regards,
Ketcher team

**Comment by dan2097** [comment]
@AndreiMazol While this isn't a bug, it is a difference in behaviour as compared to other popular sketchers e.g. Marvin JS, ChemDraw JS, JSME. Online versions of all these sketchers are accesible to verify this. Take for example cyclohexene, and bond cyclohexane to it along the double bond. In all 3 sketchers mentioned, the result will be C1CCC2=C(C1)CCCC2, while in Ketcher there will be no double bond.

**Comment by AndreiMazol** [comment]
Dear @robtree ,

I totally agree with you that behavior should be aligned with existing popular sketchers. As I mentioned above we plan to  rework  this behavior in scope of #95 after detailed analysis. 
Don't you mind if we close this issue? If you would like to follow the progress of enhancement #95, you could subscribe for it.

Best regards,
Ketcher team

**Comment by robtree** [comment]
Hello @AndreiMazol, sure, thanks for your comments and I'll follow along in #95.

**Comment by AndreiMazol** [comment]
Enhancement has been created #98 .
