### ISSUE TITLE
API_PATH not set 

### ISSUE THREAD

**Issue by jaohbib** [epam/ketcher#81]
I used the npm build to build ketcher

I  build  ketcher using the following command 
npm run build -- --api-path=server-url

so i would expect  _API_PATH_ to be equal to server-url
my browser requests /ketcher/__API_PATH__/info  which returns a 404
do i have to install the indigo docker image or is there an alternative to docker ?

**Comment by AlexanderSavelyev** [comment]
One can set --api-path=/v2 to use absolute path on the same server and configure nginx to run the service and ketcher

see instructions here
https://lifescience.opensource.epam.com/indigo/service/index.html
* nginx should be run separately. The reason for the environment with separate web server is that ketcher static files and indigo-service should be hosted on the same server and port. Otherwise REST API will not work because of CORS

* One can run nginx or any other http server which supports uwsgi (e.g. Tomcat)
* Also please see #1 for some options to run nginx

**Comment by jaohbib** [comment]
i used sudo npm run build --api-path=/v2
still not working is there a place in the generated buil i could check

**Comment by AlexanderSavelyev** [comment]
Hi @jaohbib 

Did you install docker image and configure nginx for the same endpoint according to the instructions above?

Thanks
Aleksandr

**Comment by jaohbib** [comment]
I used the following compose file 

version: '3'
services:
  nginx:
    image: nginx:1.17.10-alpine
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    links:
      - indigo_service
    depends_on:
      - indigo_service

  indigo_service:
    image: epmlsop/indigo_service
    environment:
      - PYTHONPATH=${INDIGO_SERVICE_PYTHONPATH:-/srv/indigo-python}
      - INDIGO_UWSGI_RUN_PARAMETERS=--plugin python3 --py-autoreload=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 8002:8002
    command: supervisord -n


I can reach the indigo enpoint under 127.0.0.1:8081

But i do not understand why the ketcher build process  ignors my input

**Comment by jaohbib** [comment]
![ketcher](https://user-images.githubusercontent.com/72259105/98361351-a93d9500-202b-11eb-85be-831427195a75.PNG)

**Comment by AlexanderSavelyev** [comment]
It seems that there is no ketcher in your nginx docker setup, so you need to change the api path to the host where the 8081 is accessible
Please try to set 
api_path=$your_host:8081/v2

**Comment by jaohbib** [comment]
are there plans to maintain a ketcher container  which contains an nginx and ketcher ?

**Comment by AndreiMazol** [comment]
Dear @jaohbib ,

the option you  are referred to is planned to be implemented in  the one of upcoming releases.

Best regards,
Ketcher team
