### ISSUE TITLE
Indigo Service docker problem 

### ISSUE THREAD

**Issue by DrZhong** [epam/ketcher#82]
in my docker,i run the code below:

`docker run --restart=always -d -p 8002:8002 -e "INDIGO_UWSGI_RUN_PARAMETERS=--plugin python3 --py-autoreload=1"
-e "PYTHONPATH=/srv/indigo-python" -e "PYTHONDONTWRITEBYTECODE=1" --name=indigo_service
epmlsop/indigo_service:latest /bin/sh -c "supervisord -n"`

after that i run docker ps like below
![image](https://user-images.githubusercontent.com/8085571/98230013-9b3d3500-1f95-11eb-84f5-aff9bc6ba191.png)
but i can not view the url http://localhost:8002 in my brower

there is the logs of the service
![image](https://user-images.githubusercontent.com/8085571/98230406-0f77d880-1f96-11eb-94f2-015a35c2a514.png)
 Can you tell me which step above went wrong?

**Comment by AlexanderSavelyev** [comment]
* indigo-service runs only uwsgi on 8002 port
* One needs to run nginx service and add uwsgi configuration
see instructions here
https://lifescience.opensource.epam.com/indigo/service/index.html
* nginx should be run separately. The reason for the environment with separate web server is that ketcher static files and indigo-service should be hosted on the same server and port. Otherwise REST API will not work because of CORS

* One can run nginx or any other http server which supports uwsgi (e.g. Tomcat)
* Also please see #1 for some options to run nginx

**Comment by DrZhong** [comment]
> * indigo-service runs only uwsgi on 8002 port
> * One needs to run nginx service and add uwsgi configuration
>   see instructions here
>   https://lifescience.opensource.epam.com/indigo/service/index.html
> * nginx should be run separately. The reason for the environment with separate web server is that ketcher static files and indigo-service should be hosted on the same server and port. Otherwise REST API will not work because of CORS
> * One can run nginx or any other http server which supports uwsgi (e.g. Tomcat)
> * Also please see #1 for some options to run nginx

 
Thanks, i have solved it.
