### ISSUE TITLE
502 error if apply reaction auto-mapping tool

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#985]
**Steps to Reproduce**
1. Open the structure   
[reaction_2.zip](https://github.com/epam/ketcher/files/7561080/reaction_2.zip)
2. Select reaction-automapping tool
3. Select any from drop down field
4. Click OK

**Expected behavior**
reaction auto-mapping applied to the structure
**Actual behavior**
Error is shown

**Screenshots**

![automapping](https://user-images.githubusercontent.com/93334478/142375849-3cb78c9d-8560-4de4-a0ec-cdc67e815e2a.png)
**Desktop (please complete the following information):**
 - OS: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by r1z3rISGOD** [comment]
Related issue epam/Indigo/issues/529

**Comment by karen-sarkisyan** [comment]
While running manual tests, I've encountered another manifestation if this problem, so I'll leave it here too.

**Steps**
- Checkout latest version of `release/2.4` branch
- `yarn install`, `yarn build`, `yarn serve:standalone`
- Open the structure [reaction_2.zip](https://github.com/epam/ketcher/files/7561080/reaction_2.zip)
- Select reaction-automapping tool
- Select any value from drop down field
- Click OK

**Expected behavior**
reaction auto-mapping applied to the structure

**Actual behavior**
App crashes.

For a rich error report I've started a dev server, here's what the error is:
![image](https://user-images.githubusercontent.com/18420141/143033175-4edb2365-5d4b-4c2b-adc8-7da2f22a0fe5.png)

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
